- hosts: checkers, master
  tasks:
  - name: sync catalog
    synchronize: src="../checkers" dest="{{cs_dir}}"
    tags: sync

  - name: checkers owner
    file:
      path: "{{cs_dir}}/checkers"
      owner: "{{cs_user}}"
      group: "{{cs_user}}"
      recurse: yes
    tags: sync

#  - name: install sys deps
#    apt:
#      name:
#        - g++
#      install_recommends: no

#  - name: set python3.7 as default
#    command: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1

#  - name: python deps
#    pip:
#      executable: pip3
#      name:
#        - requests
#        - pycrypto
#        - pillow
#        - aiohttp
#        - numpy
